routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/password/{pwd}', 'UserController@genPwd');
//Route::get('/user/cambia_password/{email}', 'UserController@cambiaPassword');
//Route::get('test_emails', 'UserController@testEmails');

Route::get('/', 'HomeController@index')->middleware('auth');

Auth::routes(['verify' => true]);

Route::get('/artigiano/{command}', 'ArtigianoController@showSingle')->name('ArtigianoSingle');
Route::get('/artigiano/{command}/{param}', 'ArtigianoController@show')->name('Artigiano');

Route::post('/password-change', 'UserController@passwordChange');

Route::group(['prefix' => 'share', 'as' => 'share.'], function() {
    Route::get('/shop/{shop_id}', 'ShareController@shop');
    Route::get('/shop_catalog/{shop_catalog_id}', 'ShareController@shopCatalog');
    Route::get('/shop_offer/{shop_offer_id}', 'ShareController@shopOffer');
    Route::get('/shop_offer_food/{shop_offer_food_id}', 'ShareController@shopOfferFood');
});

/*
Route::get('/phpinfo', function(){ phpinfo(); });
*/

Route::get('/storage/invoices/orders/{order}/{filename}', 'OrderController@downloadPDF');
Route::get('/storage/invoices/orders/{order}', 'OrderController@pdfHtml');

Route::group(['middleware' => ['auth', 'check.status']], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/il-mio-negozio', 'HomeController@ilMioNegozio')->name('ilMioNegozio');
    Route::get('/prices', 'SubscriptionController@prices')->name('prices');

    Route::get('profile/edit',              ['as' => 'profile.edit',           'uses' => 'UserController@editProfile']);
    Route::post('profile/update',           ['as' => 'profile.update',         'uses' => 'UserController@updateProfile']);

    Route::group(['prefix' => 'foodTypes', 'as' => 'foodTypes.'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'FoodTypeController@index']);
        Route::put('/update', ['as' => 'update', 'uses' => 'FoodTypeController@update']);
    });

    Route::get('/food/search', 'API\FoodAPIController@search');

    Route::get('/food/{food_category_id}/types', 'FoodController@getFoodTypeList');

    Route::get('/related_uoms/{unit_of_measure}', 'API\ShopCatalogAPIController@getRelatedUoms');

    Route::post('/orders/{order}/sendMessage', ['as' => 'orders.send_message', 'uses' => 'OrderController@sendMessage']);

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function() {
        Route::get('',                          ['as' => 'index',       'uses' => 'NotificationController@index']);
        Route::get('/read/{notification_id}',   ['as' => 'unread',      'uses' => 'NotificationController@read']);
        Route::put('/read/all',                 ['as' => 'unread',      'uses' => 'API\NotificationAPIController@readAll']);
        Route::put('/read/{notification_id}',   ['as' => 'read',        'uses' => 'API\NotificationAPIController@read']);
        Route::put('/unread/{notification_id}', ['as' => 'unread',      'uses' => 'API\NotificationAPIController@unread']);
        Route::delete('/all',                   ['as' => 'destroyAll',  'uses' => 'API\NotificationAPIController@destroyAll']);
        Route::delete('/{notification_id}',     ['as' => 'destroy',     'uses' => 'API\NotificationAPIController@destroy']);
    });

    Route::group(['prefix' => 'blacklist', 'as' => 'blacklist.'], function() {
        Route::get('/',                              ['as' => 'index',  'uses' => 'BlacklistController@index']);
        Route::post('/remove/{shop_id}/{user_id}',   ['as' => 'remove', 'uses' => 'BlacklistController@remove']);
    });

    Route::group(['middleware' => ['auth', 'check.admin']], function () {

        Route::resource('foodCategories', 'FoodCategoryController');

        Route::resource('foods', 'FoodController');
        Route::get('/foodCategories/{food_category_id}/check/images', 'FoodController@checkImages');
        Route::get('/foodCategories/{food_category_id}/move', 'FoodCategoryController@selectForMove');
        Route::post('/foodCategories/{food_category_id}/moveFoods', 'FoodCategoryController@moveFoods');
        Route::post('/foodCategories/{food_category_id}/moveShopCatalogs', 'FoodCategoryController@moveShopCatalogs');

        Route::resource('specials', 'SpecialController');

        Route::resource('shopTypes', 'ShopTypeController');

        Route::resource('agents', 'AgentController');

        Route::resource('paymentMethods', 'PaymentMethodController');

        Route::resource('deliveryMethods', 'DeliveryMethodController');

        Route::get('unitOfMeasures/getList', 'API\UnitOfMeasuresAPIController@index');
        Route::post('unitOfMeasures/replace', 'API\UnitOfMeasuresAPIController@replace');
        Route::resource('unitOfMeasures', 'UnitOfMeasureController');

        Route::resource('shops', 'ShopController');
		Route::post('shop/store_admin', ['as' => 'shops.store_admin', 'uses' => 'ShopController@store_admin']);
        Route::get('shop/enable/{id}', 'ShopController@enable');
        Route::get('shop/disable/{id}', 'ShopController@disable');
    	Route::get('/shops/sendAdminRegistrationEmail/{id}', 'ShopController@sendAdminRegistrationEmail');

        Route::get('shop_subscription/{shop_id}', ['as' => 'shopSubscription.edit', 'uses' => 'ShopController@editSubscription']);
        Route::post('shop_subscription/update', ['as' => 'shopSubscription.update', 'uses' => 'ShopController@updateSubscription']);

        Route::resource('users', 'UserController');
        Route::get('user/enable/{id}', 'UserController@enable');
        Route::get('user/disable/{id}', 'UserController@disable');

        Route::group(['prefix' => 'subscriptions', 'as' => 'subscriptions.'], function() {
            Route::get('/',                                ['as' => 'index',        'uses' => 'SubscriptionController@index']);
            Route::get('/{subscription}',                  ['as' => 'edit',         'uses' => 'SubscriptionController@edit']);
            Route::put('/update',                          ['as' => 'update',       'uses' => 'SubscriptionController@update']);
            Route::post('/feature/save',                   ['as' => 'feature.save', 'uses' => 'SubscriptionController@featureStore']);
            Route::put('/feature/{feature_id}',            ['as' => 'feature.update', 'uses' => 'SubscriptionController@featureUpdate']);
            Route::get('/feature/{feature_id}',            ['as' => 'feature', 'uses' => 'SubscriptionController@getFeature']);
            Route::delete('/feature/{feature_id}',  ['as' => 'feature.delete', 'uses' => 'SubscriptionController@deleteFeature']);
        });
    });


    Route::group(['middleware' => ['auth', 'check.company']], function () {

        Route::post('profile/update_company',   ['as' => 'profile.update_company', 'uses' => 'UserController@updateProfileCompany']);

        Route::get('shop/{shop_id}/food_category/{food_category_id}/types', 'ShopController@getCategoryTypes');

        Route::get('/shop/invisible', 'ShopController@invisible');
        Route::get('/shop/visible', 'ShopController@visible');

        Route::get('/publish/request', 'ShopController@publishRequest');

        //Route::resource('shopCatalogs', 'ShopCatalogController');
        Route::group(['prefix' => 'shopCatalogs', 'as' => 'shopCatalogs.'], function() {
            Route::post('',                                 ['as' => 'store',   'uses' => 'ShopCatalogController@store'])->middleware('can:add_to_catalog');
            Route::get('',                                  ['as' => 'index',   'uses' => 'ShopCatalogController@index']);
            Route::get('create',                            ['as' => 'create',  'uses' => 'ShopCatalogController@create'])->middleware('can:add_to_catalog');
            Route::get('search',                            ['as' => 'search',  'uses' => 'API\ShopCatalogAPIController@search']);
            Route::get('/type-list/{food_category_id?}',    ['as' => 'types',   'uses' => 'API\ShopCatalogAPIController@getTypesList']);
            Route::patch('{shopCatalog}',                   ['as' => 'update',  'uses' => 'ShopCatalogController@update']);
            Route::delete('{shopCatalog}',                  ['as' => 'destroy', 'uses' => 'ShopCatalogController@destroy']);
            Route::get('{shopCatalog}/active',              ['as' => 'active',    'uses' => 'ShopCatalogController@setActive']);
            Route::get('{shopCatalog}',                     ['as' => 'show',    'uses' => 'ShopCatalogController@show']);
            Route::get('{shopCatalog}/edit',                ['as' => 'edit',    'uses' => 'ShopCatalogController@edit']);

            Route::group(['prefix' => 'multi', 'as' => 'multi.'], function() {

                Route::delete('delete', ['as' => 'delete',   'uses' => 'ShopCatalogController@multiDestroy']);
                Route::post('activate', ['as' => 'activate', 'uses' => 'ShopCatalogController@multiActivate']);
                Route::post('disable',  ['as' => 'active',   'uses' => 'ShopCatalogController@multiDisable']);

            });
        });

        //Route::resource('shopOffers', 'ShopOfferController');
        Route::group(['prefix' => 'shopOffers', 'as' => 'shopOffers.'], function() {
            Route::post('',                   ['as' => 'store',    'uses' => 'ShopOfferController@store']);
            Route::get('status/{shopOffer}',  ['as' => 'status',   'uses' => 'ShopOfferController@status']);

app/Models/Food.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

/**
 * Class Food
 * @package App\Models
 * @version June 22, 2020, 7:30 am UTC
 *
 * @property \App\Models\FoodCategory $foodCategory
 * @property \App\Models\UnitOfMeasure $unitOfMeasure
 * @property integer $food_category_id
 * @property integer $unit_of_measure_id
 * @property string $name
 * @property string $description
 * @property string $type
 * @property string $image
 * @property boolean $available
 */
class Food extends Model
{

    public $table = 'foods';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';




    public $fillable = [
        'food_category_id',
        'unit_of_measure_id',
        'name',
        'description',
        'type',
        'image',
        'available'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'food_category_id' => 'integer',
        'unit_of_measure_id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'type' => 'string',
        'image' => 'string',
        'available' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'food_category_id' => 'required',
        'unit_of_measure_id' => 'required',
        'name' => 'required',
        'type' => 'required',
        'available' => 'required'
    ];

    public static $messages = [
        'food_category_id.required' => 'Selezionare un genere',
        'unit_of_measure_id.required' => 'Selezionare l\'unità di misura',
        'name.required' => 'Il nome è obbligatorio',
        'type.required' => 'La tipologia è obbligatoria',
        'available.required' => 'La disponibilità è obbligatoria'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function foodCategory()
    {
        return $this->belongsTo(\App\Models\FoodCategory::class, 'food_category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function unitOfMeasure()
    {
        return $this->belongsTo(\App\Models\UnitOfMeasure::class, 'unit_of_measure_id');
    }

    public function specials()
    {
        return $this->belongsToMany('App\Models\Special', 'food_specials');
    }
}

resources/views/foods/create.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" type="text/css" href="/fileinput/normalize.css" />
<link rel="stylesheet" type="text/css" href="/fileinput/component.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.css"/>
<script>(function(e,t,n){var r=e.querySelectorAll("html")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);</script>
@endsection

@section('content')
    <section class="content-header">
        <h1>Alimento</h1>
    </section>
    <div class="content">
        @include('flash::message')
        <div class="card card-primary">
            <div class="card-body">
                <div class="card-body">
                    {!! Form::open(['route' => 'foods.store', 'files' => true]) !!}

                        @include('foods.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @include('users.modal_preview')
@endsection

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.js"></script>
<script src="/cropimage/cropimage.js"></script>
<script src="/fileinput/custom-file-input.js"></script>
<script>

    let defaultUom = JSON.parse($("#defaultUom").val());

    $(document).ready(function(){

        setDefaultUom();

        $("#food_category_id").on('change', function(){
            setDefaultUom();
        });
    });

    function setDefaultUom(){
        let food_category_id = $("#food_category_id").val();
        $("#unit_of_measure_id").val(defaultUom[food_category_id]);
    }

    /*
    function preview_image(event)
    {
        var reader = new FileReader();
        reader.onload = function()
        {
        var output = document.getElementById('output_image');
        output.src = reader.result;
        }
        reader.readAsDataURL(event.target.files[0]);
    }
    */
</script>
@endsection

resources/views/foods/fields.blade.php
<div class="row">

    <!-- Name Field -->
    <div class="form-group col-sm-6 @error('name') has-error @enderror">
        {!! Form::label('name', __('common.name')) !!}
        {!! Form::text('name', old('name', $food->name ?? ''), ['class' => 'form-control', 'required' => true]) !!}
        @error('name')
            <div class="alert alert-danger mt-1">{{ $message }}</div>
        @enderror
    </div>

    <!-- Description Field -->
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('description', __('common.description')) !!}
        {!! Form::textarea('description', old('description', $food->description ?? ''), ['class' => 'form-control']) !!}
    </div>


    <!-- Food Category Id Field -->
    <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
        {!! Form::label('food_category_id', __('common.food_category')) !!}
        {!! Form::select('food_category_id', $arr_food_categories, old('food_category_id'), ['class' => 'form-control']) !!}
    </div>

    <!-- Type Field -->
    <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6 @error('type') has-error @enderror">
        {!! Form::label('type', 'TIPOLOGIA') !!}
        <input type="text" list="type_list" name="type" value="{{ isset($food) ? $food->type : null }}" class="form-control" required/>
        <datalist id="type_list">
            @foreach($arr_food_type as $food_type)
                <option>{{ $food_type }}</option>
            @endforeach
        </datalist>
        @error('type')
            <div class="alert alert-danger mt-1">{{ $message }}</div>
        @enderror
    </div>

    <!-- Unit Of Measure Field -->
    <div class="form-group col-sm-6 col-md-6 col-lg-6 @error('unit_of_measure_id') has-error @enderror">
        {!! Form::label('unit_of_measure_id', __('common.unit_of_measure')) !!}
        {!! Form::select('unit_of_measure_id', $arr_unit_of_measures, null, ['id' => 'unit_of_measure_id', 'class' => 'form-control', 'required' => true]) !!}
        @error('unit_of_measure_id')
            <div class="alert alert-danger mt-1">{{ $message }}</div>
        @enderror
    </div>
</div>
<div class="row">
    <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
        {!! Form::label('fileimage', __('common.image')) !!}
        <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top"
            title="Puoi modificare l'immagine del prodotto a tuo piacimento"></i>
        <div style="clear: both"></div>

        @php

        if( !empty($food->image) ){

            $foodImage = $food->image;
            if( dirname($food->image) == '.' ){
                $foodImage = url('storage/images/foods/'.NormalizeString($food->foodCategory->name).'/'.$food->image);
            }

            /* Verifico la presenza */
            $foodImage = getResizedImage(getOriginalImage($foodImage), '646x430');

            $textButton = 'Seleziona una nuova immagine';
        }else{
            $textButton = 'Seleziona immagine';
        }
        @endphp

        <div class="box">
            <p id="img-suggestion" class="text-primary">Puoi cambiare questa immagine in qualsiasi momento.<br/>File ammessi > .jpg - Max 10 mb - dimensioni minime di 646x430</p>
            <input type="file" name="fileimage" accept="image/jpeg" id="fileimage" class="js inputfile inputfile-1" data-multiple-caption="{count} immagine selezionata" />
            <label for="fileimage" class="lbl-fileimage"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span id="btn-fileimage">{{ $textButton }}</span></label>
        </div>

        <div style="clear: both"></div>

        @if( old('food_image', $foodImage ?? null) )
            <img id="output_image" src="{{ old('food_image', $foodImage ?? null) }}" style="width: 100%; margin-top: 10px;">
        @else
            <img id="output_image" src="/images/no-image.png" style="width: 100%; margin-top: 10px;" />
        @endif
        <input type="hidden" id="output_image_type" name="output_image_type" value="">
        <input type="hidden" id="output_image_name" name="output_image_name" value="">
        <input type="hidden" id="output_image_data" name="output_image_data" value="">

        @error('fileimage')
            <div class="alert alert-danger mt-1">{{ $message }}</div>
        @enderror

        {!! Form::hidden('food_image', null, ['id' => 'food_image']) !!}
    </div>
    {{--
    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
        <!-- Image Field -->
        <div class="form-group">
            {!! Form::label('fileimage', __('common.image')) !!}
            <div style="clear: both"></div>
            <span class="text-success"><p id="img-suggestion" class="text-primary">Puoi cambiare questa immagine in qualsiasi momento. L'immagine verrà ritagliata in un formato 3:2 File ammessi > .jpg - Max 10 mb - dimensioni minime di 646x430</p></span>
            <br>
            {!! Form::file('fileimage', ['accept' => $image_type, 'onchange' => 'preview_image(event)']) !!}
            <div style="clear: both"></div>

            @if( old('food_image', $food->image ?? null) )
                <img id="output_image" src="{{ asset('/storage/images/foods/'.NormalizeString($food->foodCategory->name).'/'.$food->image) }}" class="thumbnail mt-1" style="width: 100%">
            @else
                <img id="output_image" style="margin-top: 10px; width: 400px"/>
            @endif

            {!! Form::hidden('food_image', null, ['id' => 'food_image']) !!}

            @error('fileimage')
                <div class="alert alert-danger mt-1">{{ $message }}</div>
            @enderror
        </div>
    </div>
     --}}

    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
        <div class="form-group">
            {!! Form::label('food_specials[]', 'Caratteristiche speciali') !!}
            {!! Form::select('food_specials[]', $specials->pluck('name', 'id'), old('food_specials[]', isset($food) ? $food->specials()->pluck('special_id')->toArray() ?? null : null), ['class' => 'form-control', 'multiple' => true, 'style' => 'height: 600px']) !!}
            <small class="press-ctrl">Tenere premuto CTRL per selezionare più caratteristiche speciali</small>
        </div>
    </div>
</div>

<div class="row">
    <!-- Available Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('available', __('common.available')) !!}
        <label class="checkbox-inline">
            {!! Form::hidden('available', 0) !!}
            {!! Form::checkbox('available', '1', null) !!}
        </label>
    </div>

    <input type="hidden" id="defaultUom" value="{{ $defaultUom }}">

    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit(__('common.save'), ['class' => 'btn btn-primary btn-full']) !!}
        <a href="{{ route('foods.index') }}" class="btn btn-default btn-full">{{ __('common.cancel') }}</a>
    </div>
</div>

resources/views/foods/index.blade.php
@extends('adminlte::page')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Alimenti <span class="badge badge-success">{{ $tot_alimenti }}</span></h1>
        <div class="pull-right  float-right d-none d-sm-block" >
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('foods.create') }}">Aggiungi nuovo</a>
        </div>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
       
        <div class="card card-primary">
            <div class="card-body">
                    @include('foods.table')
            </div>
        </div>
        
    </div>
@endsection

resources/views/foods/show.blade.php
@extends('adminlte::page')

@section('content')
    <section class="content-header">
        <h1>
            Food
        </h1>
    </section>
    <div class="content">
        <div class="card card-primary">
            <div class="card-body">
                <div class="row" style="padding-left: 20px">
                    @include('foods.show_fields')
                    <a href="{{ route('foods.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/foods/table.blade.php
<div class="card card-primary">
    <div class="card-header" style="background-color:#13bf9e !important;margin-bottom:20px ">
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <label>Cerca per genere ({{$tot_generi}})</label>
                {!! Form::select('genere', $generi, null, ['id' => 'food_category', 'class' => 'form-control']) !!}
            </div>
            <div class="col-sm-12 col-md-4">
                <label>Cerca per tipologia (<span id="tot_tipologie">{{ $tot_tipologie }}</span>)</label>
                {!! Form::select('tipologia', $tipologie, null, ['id' => 'food_type', 'class' => 'form-control']) !!}
            </div>
            <div class="col-sm-12 col-md-4">
                <label>Cerca per parola chiave:</label>
                <input type="search" class="form-control " placeholder="cerca per parola chiave" aria-controls="agents-table" name="searchname" id="searchname">
            </div>
        </div>
    </div>
</div>

<table class="table" id="foods-table" style="width: 100% !important">
    <thead>
        <tr>
            <th style="width: 150px">{{__('common.action')}}</th>
            <th>{{__('common.name')}}</th>
            <th>{{__('common.image')}}</th>
            <th>{{__('common.description')}}</th>
            <th>{{__('common.food_category')}}</th>
            <th>UdM</th>
            <th><span title="Disponibile">Disp.</span></th>
            <th>fc</th>
        </tr>
    </thead>
</table>

@section('js')
<script>

var intervalSearch = null;
var table = null;

$(function () {

    table = $('#foods-table').DataTable({
        "language": {
            url: "{{ url('js/Italian.json') }}"
        },
        dom: "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'p>r>"+
            "<'row'<'col-sm-12't>>"+
            "<'row'<'col-sm-12 col-md-6'i><'col-sm-12 col-md-6'p>>",
        processing: true,
        serverSide: true,
        stateSave: true,
        stateSave: true,
        "initComplete": function (settings, json) {
            $("#foods-table").wrap("<div style='overflow:auto; width:100%;position:relative;'></div>");
        },
        //paginate: true,
        //pageLength: 10,
        //ajax: '{{ route('foods.index') }}',
        ajax: {
            url: '{{ route('foods.index') }}',
            data: function (d) {
                d.searchname = $('#searchname').val(),
                d.genere = $('select[name=genere]').val(),
                d.tipologia = $('select[name=tipologia]').val()
            }
        },
        columns: [
            // {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'action', name: 'action', orderable: false, searchable: false, width: "10%"},
            {data: 'name', name: 'f.name', width: 200},
            {data: 'image', name: 'f.image', orderable: false, searchable: false},
            {data: 'description', name: 'f.description'},
            {data: 'category',  name: 'category', searchable: false, orderData: 7},
            {data: 'UnitOfMeasure', name: 'u.name', searchable: false},
            {data: 'available', name: 'f.available', searchable: false},
            {data: 'foodCategory', name: 'foodCategory', searchable: false, visible: false},
        ]
    });

    $('[data-toggle="tooltip"]').tooltip();

    $("#searchname").keyup(function(){
        if( intervalSearch !== null ){
            clearInterval(intervalSearch);
        }

        intervalSearch = setInterval(function(){
            clearInterval(intervalSearch);
            search();
        }, 500, table);
    });

    $("select[name=genere]").change(function(){
        table.draw();
        loadFoodType($(this).val(), 'food_type');
    });

    $("select[name=tipologia]").change(function(){
        table.draw();
    });

});

search = () => {
    table.search( $("#searchname").val() ).draw();
}


loadFoodType = (food_category_id, element_id, sel_value = null) => {

    $('#'+element_id).empty();

    if( food_category_id != '' ){

        $.ajax({
            url: '/food/'+food_category_id+'/types',
            data: {
                "_token": "{{ csrf_token() }}",
            },
            type: 'GET',
            dataType: 'json',
            statusCode: {
                401: function() {
                    document.location.href = '/login';
                },
                419: function() {
                    document.location.href = '/login';
                }
            },
            success: function(res){
                var element = document.getElementById(element_id);
                var option = document.createElement("option");
                option.text = 'Cerca in tutte le tipologie';
                option.value = '';
                element.add(option);

                $("#tot_tipologie").text(res.count);

                for(var i=0; i<res.count; i++){
                    option = document.createElement("option");
                    option.text = res['Food Type List'][i];
                    option.value = res['Food Type List'][i];
                    element.add(option);

                    if( sel_value ){
                        if( option.text === sel_value ){
                            element.selectedIndex = (i+1);
                        }
                    }

                }
            }
        });

    }else{

        var element = document.getElementById(element_id);
        var option = document.createElement("option");
        option.text = 'Cerca in tutte le tipologie';
        option.value = '';
        element.add(option);

        $("#tot_tipologie").text(0);

    }
}

</script>
@endsection