routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/password/{pwd}', 'UserController@genPwd');
//Route::get('/user/cambia_password/{email}', 'UserController@cambiaPassword');
//Route::get('test_emails', 'UserController@testEmails');

Route::get('/', 'HomeController@index')->middleware('auth');

Auth::routes(['verify' => true]);

Route::get('/artigiano/{command}', 'ArtigianoController@showSingle')->name('ArtigianoSingle');
Route::get('/artigiano/{command}/{param}', 'ArtigianoController@show')->name('Artigiano');

Route::post('/password-change', 'UserController@passwordChange');

Route::group(['prefix' => 'share', 'as' => 'share.'], function() {
    Route::get('/shop/{shop_id}', 'ShareController@shop');
    Route::get('/shop_catalog/{shop_catalog_id}', 'ShareController@shopCatalog');
    Route::get('/shop_offer/{shop_offer_id}', 'ShareController@shopOffer');
    Route::get('/shop_offer_food/{shop_offer_food_id}', 'ShareController@shopOfferFood');
});

/*
Route::get('/phpinfo', function(){ phpinfo(); });
*/

Route::get('/storage/invoices/orders/{order}/{filename}', 'OrderController@downloadPDF');
Route::get('/storage/invoices/orders/{order}', 'OrderController@pdfHtml');

Route::group(['middleware' => ['auth', 'check.status']], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/il-mio-negozio', 'HomeController@ilMioNegozio')->name('ilMioNegozio');
    Route::get('/prices', 'SubscriptionController@prices')->name('prices');

    Route::get('profile/edit',              ['as' => 'profile.edit',           'uses' => 'UserController@editProfile']);
    Route::post('profile/update',           ['as' => 'profile.update',         'uses' => 'UserController@updateProfile']);

    Route::group(['prefix' => 'foodTypes', 'as' => 'foodTypes.'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'FoodTypeController@index']);
        Route::put('/update', ['as' => 'update', 'uses' => 'FoodTypeController@update']);
    });

    Route::get('/food/search', 'API\FoodAPIController@search');

    Route::get('/food/{food_category_id}/types', 'FoodController@getFoodTypeList');

    Route::get('/related_uoms/{unit_of_measure}', 'API\ShopCatalogAPIController@getRelatedUoms');

    Route::post('/orders/{order}/sendMessage', ['as' => 'orders.send_message', 'uses' => 'OrderController@sendMessage']);

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function() {
        Route::get('',                          ['as' => 'index',       'uses' => 'NotificationController@index']);
        Route::get('/read/{notification_id}',   ['as' => 'unread',      'uses' => 'NotificationController@read']);
        Route::put('/read/all',                 ['as' => 'unread',      'uses' => 'API\NotificationAPIController@readAll']);
        Route::put('/read/{notification_id}',   ['as' => 'read',        'uses' => 'API\NotificationAPIController@read']);
        Route::put('/unread/{notification_id}', ['as' => 'unread',      'uses' => 'API\NotificationAPIController@unread']);
        Route::delete('/all',                   ['as' => 'destroyAll',  'uses' => 'API\NotificationAPIController@destroyAll']);
        Route::delete('/{notification_id}',     ['as' => 'destroy',     'uses' => 'API\NotificationAPIController@destroy']);
    });

    Route::group(['prefix' => 'blacklist', 'as' => 'blacklist.'], function() {
        Route::get('/',                              ['as' => 'index',  'uses' => 'BlacklistController@index']);
        Route::post('/remove/{shop_id}/{user_id}',   ['as' => 'remove', 'uses' => 'BlacklistController@remove']);
    });

    Route::group(['middleware' => ['auth', 'check.admin']], function () {

        Route::resource('foodCategories', 'FoodCategoryController');

        Route::resource('foods', 'FoodController');
        Route::get('/foodCategories/{food_category_id}/check/images', 'FoodController@checkImages');
        Route::get('/foodCategories/{food_category_id}/move', 'FoodCategoryController@selectForMove');
        Route::post('/foodCategories/{food_category_id}/moveFoods', 'FoodCategoryController@moveFoods');
        Route::post('/foodCategories/{food_category_id}/moveShopCatalogs', 'FoodCategoryController@moveShopCatalogs');

        Route::resource('specials', 'SpecialController');

        Route::resource('shopTypes', 'ShopTypeController');

        Route::resource('agents', 'AgentController');

        Route::resource('paymentMethods', 'PaymentMethodController');

        Route::resource('deliveryMethods', 'DeliveryMethodController');

        Route::get('unitOfMeasures/getList', 'API\UnitOfMeasuresAPIController@index');
        Route::post('unitOfMeasures/replace', 'API\UnitOfMeasuresAPIController@replace');
        Route::resource('unitOfMeasures', 'UnitOfMeasureController');

        Route::resource('shops', 'ShopController');
		Route::post('shop/store_admin', ['as' => 'shops.store_admin', 'uses' => 'ShopController@store_admin']);
        Route::get('shop/enable/{id}', 'ShopController@enable');
        Route::get('shop/disable/{id}', 'ShopController@disable');
    	Route::get('/shops/sendAdminRegistrationEmail/{id}', 'ShopController@sendAdminRegistrationEmail');

        Route::get('shop_subscription/{shop_id}', ['as' => 'shopSubscription.edit', 'uses' => 'ShopController@editSubscription']);
        Route::post('shop_subscription/update', ['as' => 'shopSubscription.update', 'uses' => 'ShopController@updateSubscription']);

        Route::resource('users', 'UserController');
        Route::get('user/enable/{id}', 'UserController@enable');
        Route::get('user/disable/{id}', 'UserController@disable');

        Route::group(['prefix' => 'subscriptions', 'as' => 'subscriptions.'], function() {
            Route::get('/',                                ['as' => 'index',        'uses' => 'SubscriptionController@index']);
            Route::get('/{subscription}',                  ['as' => 'edit',         'uses' => 'SubscriptionController@edit']);
            Route::put('/update',                          ['as' => 'update',       'uses' => 'SubscriptionController@update']);
            Route::post('/feature/save',                   ['as' => 'feature.save', 'uses' => 'SubscriptionController@featureStore']);
            Route::put('/feature/{feature_id}',            ['as' => 'feature.update', 'uses' => 'SubscriptionController@featureUpdate']);
            Route::get('/feature/{feature_id}',            ['as' => 'feature', 'uses' => 'SubscriptionController@getFeature']);
            Route::delete('/feature/{feature_id}',  ['as' => 'feature.delete', 'uses' => 'SubscriptionController@deleteFeature']);
        });
    });


    Route::group(['middleware' => ['auth', 'check.company']], function () {

        Route::post('profile/update_company',   ['as' => 'profile.update_company', 'uses' => 'UserController@updateProfileCompany']);

        Route::get('shop/{shop_id}/food_category/{food_category_id}/types', 'ShopController@getCategoryTypes');

        Route::get('/shop/invisible', 'ShopController@invisible');
        Route::get('/shop/visible', 'ShopController@visible');

        Route::get('/publish/request', 'ShopController@publishRequest');

        //Route::resource('shopCatalogs', 'ShopCatalogController');
        Route::group(['prefix' => 'shopCatalogs', 'as' => 'shopCatalogs.'], function() {
            Route::post('',                                 ['as' => 'store',   'uses' => 'ShopCatalogController@store'])->middleware('can:add_to_catalog');
            Route::get('',                                  ['as' => 'index',   'uses' => 'ShopCatalogController@index']);
            Route::get('create',                            ['as' => 'create',  'uses' => 'ShopCatalogController@create'])->middleware('can:add_to_catalog');
            Route::get('search',                            ['as' => 'search',  'uses' => 'API\ShopCatalogAPIController@search']);
            Route::get('/type-list/{food_category_id?}',    ['as' => 'types',   'uses' => 'API\ShopCatalogAPIController@getTypesList']);
            Route::patch('{shopCatalog}',                   ['as' => 'update',  'uses' => 'ShopCatalogController@update']);
            Route::delete('{shopCatalog}',                  ['as' => 'destroy', 'uses' => 'ShopCatalogController@destroy']);
            Route::get('{shopCatalog}/active',              ['as' => 'active',    'uses' => 'ShopCatalogController@setActive']);
            Route::get('{shopCatalog}',                     ['as' => 'show',    'uses' => 'ShopCatalogController@show']);
            Route::get('{shopCatalog}/edit',                ['as' => 'edit',    'uses' => 'ShopCatalogController@edit']);

            Route::group(['prefix' => 'multi', 'as' => 'multi.'], function() {

                Route::delete('delete', ['as' => 'delete',   'uses' => 'ShopCatalogController@multiDestroy']);
                Route::post('activate', ['as' => 'activate', 'uses' => 'ShopCatalogController@multiActivate']);
                Route::post('disable',  ['as' => 'active',   'uses' => 'ShopCatalogController@multiDisable']);

            });
        });

        //Route::resource('shopOffers', 'ShopOfferController');
        Route::group(['prefix' => 'shopOffers', 'as' => 'shopOffers.'], function() {
            Route::post('',                   ['as' => 'store',    'uses' => 'ShopOfferController@store']);
            Route::get('status/{shopOffer}',  ['as' => 'status',   'uses' => 'ShopOfferController@status']);

app/Models/ShopOffer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ShopOffer
 * @package App\Models
 * @version June 26, 2020, 6:28 pm UTC
 *
 * @property \App\Models\Shop $shop
 * @property \Illuminate\Database\Eloquent\Collection $shopOfferFoods
 * @property integer $shop_id
 * @property string $name
 * @property string $description
 * @property string $image_path
 * @property string $start_date
 * @property string $end_date
 * @property integer $count_purchased
 * @property string $status
 */
class ShopOffer extends Model
{

    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public $table = 'shop_offers';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public $fillable = [
        'shop_id',
        'name',
        'description',
        'image_path',
        'start_date',
        'end_date',
        'count_purchased',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'shop_id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'image_path' => 'string',
        'start_date' => 'date',
        'end_date' => 'date',
        'count_purchased' => 'integer',
        'status' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'shop_id' => 'required',
        'start_date' => 'required|date',
        'end_date' => 'required|date|after_or_equal:start_date'
    ];

    /**
     * Validation messages
     *
     * @var array
     */
    public static $messages = [
        'start_date.required' => 'Inserire la data inizio',
        'end_date.required' => 'Inserire la data fine',
        'end_date.after_or_equal' => 'La data fine deve essere uguale o successiva alla data inizio',
        'name.required' => 'Titolo offerta assente',
        'catalog_id.required' => 'Selezionare almeno un prodotto dal catalogo',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function shop()
    {
        return $this->belongsTo(\App\Models\Shop::class, 'shop_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function shopOfferFoods()
    {
        return $this->hasMany(\App\Models\ShopOfferFood::class, 'shop_offer_id');
    }
}

resources/views/shop_offers/index.blade.php
@extends('adminlte::page')
@section('content')
@if(Auth::user()->subscription->subscription != 'free')
    <div class="content padding-bottom-plus">

        <section class="content-header">
            <h1 class="pull-left">Le tue offerte</h1>
            <div class="row">
                <div class="col-md-12">
                    <div class="accordion" id="accordionExample">
                        <h2 class="m-0">
                            <button class="btn btn-link btn-block text-left mx-0 px-0" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                <i class="far fa-list-alt"></i> Legenda
                                <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Per ogni offerta sono previsti 5 stati a seconda delle tue esigenze. Puoi cambiarli facilmente cliccando sul bottone nella colonna stato oppure dal dettaglio dell'offerta"></i>
                            </button>
                        </h2>
                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="table-responsive">
                                <table class="table legenda">
                                    <tbody>
                                        <tr><td class="p-1"><strong>Offerta in bozza</strong> > non è attivata, pertanto non visibile ne' tantomeno programmata</td></tr>
                                        <tr><td class="p-1 table-warning"><strong>Offerta programmata</strong> > è attivata ma diventerà automaticamente visibile e ordinabile solo alla data prevista e fino alla data di scadenza</td></tr>
                                        <tr><td class="p-1 table-success"><strong>Offerta in corso</strong> > è attiva a tutti gli effetti, visibile e quindi ordinabile dagli utenti</td></tr>
                                        <tr><td class="p-1 table-danger"><strong>Offerta sospesa</strong> > è sospesa e pertanto non visibile e non ordinabile</td></tr>
                                        <tr><td class="p-1 table-secondary"><strong>Offerta scaduta</strong> > essendo trascorsa la data di scadenza l'offerta è stata automaticamente resa non più visibile</td></tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="clearfix"></div>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <div class="clearfix"></div>
        <div class="card card-primary">
            <div class="card-body">
                @include('shop_offers.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@else
<div class="modal-danger" align="center">
  <p><strong>Per gestire le offerte occorre avere un piano di abbonamento a pagamento.</strong></p>
  <p><a href="https://backend.primascelta.biz/prices/" target="_blank"><strong><u>Desidero vedere i piani di abbonamento disponibili</u></strong></a></p>
</div>
@endif
@endsection

@section('js')
<script>
$(function () {

    $('#shopOffers-table').DataTable({
        "language": {
            url: "{{ url('js/Italian.json') }}"
        },
        paging:   true,
        "initComplete": function (settings, json) {
            $("#shopOffers-table").wrap("<div style='overflow:auto; width:100%;position:relative;'></div>");
        },
        pageLength: 10,
        stateSave: true,
        order: [[ 3, "desc" ]],
        columnDefs: [
            { width: "10%", orderable: false, targets: 0 },
            { width: "150px", orderable: false, targets: 1 }
        ]
    });
});

deleteOffer = (shop_offer_id) => {
    showConfirm("Offerta", 'bg-danger', "Intendi cancellare in modo permanente questa offerta?", execDeleteOffer, [shop_offer_id]);
}

execDeleteOffer = (shop_offer_id) => {
    $.ajax({
        url: `/shopOffers/${shop_offer_id}`,
        data: {
            "_token": "{{ csrf_token() }}"
        },
        type: 'DELETE',
        dataType: 'json',
        statusCode: {
            401: function() {
                document.location.href = '/login';
            },
            419: function() {
                document.location.href = '/login';
            }
        },
        success: function(data){
            console.log(data);
            if( data.status == 'ok' ){
                document.location.href = "/shopOffers";
            }else if( data.status == 'error' ){
                alert(data.msg);
            }
        }
    });
}
</script>
@endsection

resources/views/shop_offers/modal_search_catalog.blade.php
<div class="modal fade" id="modal-search-catalog" aria-hidden="true" data-backdrop="static" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h4 class="modal-title">Aggiungi un nuovo prodotto a questa offerta</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="frm-search-catalog">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                {!! Form::label('search_catalog_name', 'Cerca un prodotto nel tuo catalogo') !!}
                                {!! Form::text('search_catalog_name', null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {!! Form::label('search_catalog_category', 'Genere') !!}
                                {!! Form::select('search_catalog_category', $foodCategoryList, null,  ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {!! Form::label('search_catalog_type', 'Categoria') !!}
                                {!! Form::select('search_catalog_type', [], null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>
                </form>
                <div class="compact-mode-container text-right" style="display: none;">
                    <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                        <input type="checkbox" class="custom-control-input" id="compact_mode">
                        {!! Form::label('compact_mode', 'Visualizzazione compatta', ['class' => 'custom-control-label']) !!}
                    </div>
                </div>
                <div style="max-height: 300px; overflow: auto;">
                    <div class="table-responsive">
                        <table class="table">
                            <tbody id="catalog_search_results"></tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/shop_offers/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="content">
        <div class="card card-primary">
            @php
            $bgcolor = '';
            $order_status = '';
            if( $shopOffer->status === 'available' && $shopOffer->start_date->isFuture() ):
                $bgcolor='bg-warning';
                $order_status = 'Offerta programmata';
            elseif( $shopOffer->status === 'available' && $shopOffer->start_date->isPast() && $shopOffer->end_date->addDays(1)->isFuture() ):
                $bgcolor='bg-success';
                $order_status = 'Offerta in corso';
            elseif( $shopOffer->end_date->addDays(1)->isPast() ):
                $bgcolor='bg-secondary';
                $order_status = 'Offerta scaduta';
            elseif( $shopOffer->status === 'cancelled' ):
                $bgcolor='bg-danger';
                $order_status = 'Offerta sospesa';
            endif
            @endphp
            <div class="card-header {{ $bgcolor }}">
                {{ $order_status }}
            </div>
            <div class="card-body">

                @include('shop_offers.show_fields')

                <a href="{{ route('shopOffers.index') }}" class="btn btn-default">Indietro</a>
            </div>
        </div>
    </div>
@endsection

resources/views/shop_offers/table.blade.php
@can('add_to_catalog')
	@can('add_offer')
<a class="btn btn-add btn-add-offer bg-success btn-lg d-none d-sm-none d-md-block mb-4" href="{{ route('shopOffers.create') }}">+</a>
	@else
		<center class="alert alert-danger">
			<strong>Per gestire le offerte occorre avere un piano di abbonamento a pagamento</strong>
			<p><i><u><a target="_blank" href="https://www.primascelta.biz/prezzi/">Vedi i piani di abbonamento</a></u></i></p>
		</center>
	@endcan
@endcan
@if( count($shopOffers) == 0 )
        <p class="text-center text-success font-weight-bold">
            AL MOMENTO NON HAI OFFERTE IN CORSO
        </p>
    @else
<table class="table table-hover shop-offers-table" id="shopOffers-table">
    <thead>
        <tr>
            <th>Azioni</th>
            <th>Immagine</th>
            <th>Nome</th>
            <th>Inizio</th>
            <th>Fine</th>
        </tr>
    </thead>
    <tbody>
    @foreach($shopOffers as $shopOffer)
        <tr
        @if( $shopOffer->status === 'available' && $shopOffer->start_date->isPast() && $shopOffer->end_date->addDays(1)->isFuture() )
        class="table-success"
        @elseif( $shopOffer->status === 'available' && $shopOffer->start_date->isFuture() )
        class="table-warning"
        @elseif( $shopOffer->status === 'available' && $shopOffer->end_date->addDays(1)->isPast() )
        class="table-secondary"
        @elseif( $shopOffer->status === 'cancelled' )
        class="table-danger"
        @endif
        >
            <td>
                <div class="m-2">
                    <div class="text-center" style="display: block; min-width: 130px !important;">
                        <a href="{{ route('shopOffers.show', [$shopOffer->id]) }}" class='btn btn-primary btn-sm' title="ANTEPRIMA"><i class="fa fa-eye"></i></a>
                        <a href="{{ route('shopOffers.edit', [$shopOffer->id]) }}" class='btn btn-warning btn-sm' title="MODIFICA"><i class="fas fa-edit"></i></a>
                        @if( ($shopOffer->status === 'available' && $shopOffer->start_date->isFuture()) ||
                            ($shopOffer->status === 'available' && $shopOffer->end_date->addDays(1)->isPast()) ||
                            $shopOffer->status === 'cancelled' ||
                            $shopOffer->status === 'draft' )
                            {!! Form::button('<i class="fas fa-trash"></i>', ['class' => 'btn btn-danger btn-sm', 'onclick' => "deleteOffer($shopOffer->id)", 'title' => "ELIMINA"]) !!}
                        @endif
                    </div>

                    @if($shopOffer->status === 'draft')
                    <a href="{{ route('shopOffers.status', ['shopOffer' => $shopOffer->id]) }}" class="btn btn-sm btn-block mt-1">
                        <i class="fas fa-times"></i> Bozza
                    </a>
                    @elseif($shopOffer->status === 'available' && $shopOffer->start_date->isFuture())
                    <a href="{{ route('shopOffers.status', ['shopOffer' => $shopOffer->id]) }}" class="btn btn-sm btn-block btn-warning mt-1" >
                        <i class="fas fa-check"></i> Programmata
                    </a>
                    @elseif($shopOffer->status === 'available' && $shopOffer->start_date->isPast() && $shopOffer->end_date->addDays(1)->isFuture())
                    <a href="{{ route('shopOffers.status', ['shopOffer' => $shopOffer->id]) }}" class="btn btn-sm btn-block btn-success mt-1">
                        <i class="fas fa-check"></i> Attiva
                    </a>
                    @elseif(  $shopOffer->end_date->addDays(1)->isPast() )
                    <a href="{{ route('shopOffers.status', ['shopOffer' => $shopOffer->id]) }}" class="btn btn-sm btn-block btn-secondary mt-1">
                        <i class="fas fa-stopwatch"></i> Scaduta
                    </a>
                    @elseif($shopOffer->status === 'cancelled')
                    <a href="{{ route('shopOffers.status', ['shopOffer' => $shopOffer->id]) }}" class="btn btn-sm btn-block btn-danger mt-1">
                        <i class="fas fa-times-circle"></i> Sospesa
                    </a>
                    @endif
                </div>
            </td>
            <td>
                @if( $shopOffer->shopOfferFoods->count() > 1 )
                    <img src="/images/offer.png" style="width: 100%">
                @elseif( $shopOffer->shopOfferFoods->count() === 1 )
                    @if( !empty($shopOffer->shopOfferFoods[0]->food_image) )
                        <img src="{{ getResizedImage(getOriginalImage($shopOffer->shopOfferFoods[0]->food_image), '230x154') }}" style="width: 100%">
                    @elseif( $shopOffer->shopOfferFoods[0]->shopCatalog )
                        @if( !empty($shopOffer->shopOfferFoods[0]->shopCatalog->food_image) )
                            <img src="{{ getResizedImage(getOriginalImage($shopOffer->shopOfferFoods[0]->shopCatalog->food_image), '230x154') }}" style="width: 100%">
                        @elseif( $shopOffer->shopOfferFoods[0]->shopCatalog->food )
                            <img src="{{ getResizedImage(getOriginalImage(asset('/storage/images/foods/'.NormalizeString($shopOffer->shopOfferFoods[0]->shopCatalog->food->foodCategory->name).'/'.$shopOffer->shopOfferFoods[0]->shopCatalog->food->image)), '230x154') }}" style="width: 100%">
                        @endif
                    @endif
                @endif
            </td>
            <td>{{ $shopOffer->name }}</td>
            <td><span style="display: none">{{ $shopOffer->start_date->format('Ymd') }}</span>{{ $shopOffer->start_date->format('d/m/Y') }}</td>
            <td><span style="display: none">{{ $shopOffer->end_date->format('Ymd') }}</span>{{ $shopOffer->end_date->format('d/m/Y') }}</td>
        </tr>
    @endforeach
    </tbody>
</table>
 @endif
@can('add_to_catalog')
	@can('add_offer')
<a class="btn btn-add btn-add-offer bg-success btn-lg d-md-block mt-4" href="{{ route('shopOffers.create') }}">+</a>
	@endcan
@endcan