routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/password/{pwd}', 'UserController@genPwd');
//Route::get('/user/cambia_password/{email}', 'UserController@cambiaPassword');
//Route::get('test_emails', 'UserController@testEmails');

Route::get('/', 'HomeController@index')->middleware('auth');

Auth::routes(['verify' => true]);

Route::get('/artigiano/{command}', 'ArtigianoController@showSingle')->name('ArtigianoSingle');
Route::get('/artigiano/{command}/{param}', 'ArtigianoController@show')->name('Artigiano');

Route::post('/password-change', 'UserController@passwordChange');

Route::group(['prefix' => 'share', 'as' => 'share.'], function() {
    Route::get('/shop/{shop_id}', 'ShareController@shop');
    Route::get('/shop_catalog/{shop_catalog_id}', 'ShareController@shopCatalog');
    Route::get('/shop_offer/{shop_offer_id}', 'ShareController@shopOffer');
    Route::get('/shop_offer_food/{shop_offer_food_id}', 'ShareController@shopOfferFood');
});

/*
Route::get('/phpinfo', function(){ phpinfo(); });
*/

Route::get('/storage/invoices/orders/{order}/{filename}', 'OrderController@downloadPDF');
Route::get('/storage/invoices/orders/{order}', 'OrderController@pdfHtml');

Route::group(['middleware' => ['auth', 'check.status']], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/il-mio-negozio', 'HomeController@ilMioNegozio')->name('ilMioNegozio');
    Route::get('/prices', 'SubscriptionController@prices')->name('prices');

    Route::get('profile/edit',              ['as' => 'profile.edit',           'uses' => 'UserController@editProfile']);
    Route::post('profile/update',           ['as' => 'profile.update',         'uses' => 'UserController@updateProfile']);

    Route::group(['prefix' => 'foodTypes', 'as' => 'foodTypes.'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'FoodTypeController@index']);
        Route::put('/update', ['as' => 'update', 'uses' => 'FoodTypeController@update']);
    });

    Route::get('/food/search', 'API\FoodAPIController@search');

    Route::get('/food/{food_category_id}/types', 'FoodController@getFoodTypeList');

    Route::get('/related_uoms/{unit_of_measure}', 'API\ShopCatalogAPIController@getRelatedUoms');

    Route::post('/orders/{order}/sendMessage', ['as' => 'orders.send_message', 'uses' => 'OrderController@sendMessage']);

    Route::group(['prefix' => 'notifications', 'as' => 'notifications.'], function() {
        Route::get('',                          ['as' => 'index',       'uses' => 'NotificationController@index']);
        Route::get('/read/{notification_id}',   ['as' => 'unread',      'uses' => 'NotificationController@read']);
        Route::put('/read/all',                 ['as' => 'unread',      'uses' => 'API\NotificationAPIController@readAll']);
        Route::put('/read/{notification_id}',   ['as' => 'read',        'uses' => 'API\NotificationAPIController@read']);
        Route::put('/unread/{notification_id}', ['as' => 'unread',      'uses' => 'API\NotificationAPIController@unread']);
        Route::delete('/all',                   ['as' => 'destroyAll',  'uses' => 'API\NotificationAPIController@destroyAll']);
        Route::delete('/{notification_id}',     ['as' => 'destroy',     'uses' => 'API\NotificationAPIController@destroy']);
    });

    Route::group(['prefix' => 'blacklist', 'as' => 'blacklist.'], function() {
        Route::get('/',                              ['as' => 'index',  'uses' => 'BlacklistController@index']);
        Route::post('/remove/{shop_id}/{user_id}',   ['as' => 'remove', 'uses' => 'BlacklistController@remove']);
    });

    Route::group(['middleware' => ['auth', 'check.admin']], function () {

        Route::resource('foodCategories', 'FoodCategoryController');

        Route::resource('foods', 'FoodController');
        Route::get('/foodCategories/{food_category_id}/check/images', 'FoodController@checkImages');
        Route::get('/foodCategories/{food_category_id}/move', 'FoodCategoryController@selectForMove');
        Route::post('/foodCategories/{food_category_id}/moveFoods', 'FoodCategoryController@moveFoods');
        Route::post('/foodCategories/{food_category_id}/moveShopCatalogs', 'FoodCategoryController@moveShopCatalogs');

        Route::resource('specials', 'SpecialController');

        Route::resource('shopTypes', 'ShopTypeController');

        Route::resource('agents', 'AgentController');

        Route::resource('paymentMethods', 'PaymentMethodController');

        Route::resource('deliveryMethods', 'DeliveryMethodController');

        Route::get('unitOfMeasures/getList', 'API\UnitOfMeasuresAPIController@index');
        Route::post('unitOfMeasures/replace', 'API\UnitOfMeasuresAPIController@replace');
        Route::resource('unitOfMeasures', 'UnitOfMeasureController');

        Route::resource('shops', 'ShopController');
		Route::post('shop/store_admin', ['as' => 'shops.store_admin', 'uses' => 'ShopController@store_admin']);
        Route::get('shop/enable/{id}', 'ShopController@enable');
        Route::get('shop/disable/{id}', 'ShopController@disable');
    	Route::get('/shops/sendAdminRegistrationEmail/{id}', 'ShopController@sendAdminRegistrationEmail');

        Route::get('shop_subscription/{shop_id}', ['as' => 'shopSubscription.edit', 'uses' => 'ShopController@editSubscription']);
        Route::post('shop_subscription/update', ['as' => 'shopSubscription.update', 'uses' => 'ShopController@updateSubscription']);

        Route::resource('users', 'UserController');
        Route::get('user/enable/{id}', 'UserController@enable');
        Route::get('user/disable/{id}', 'UserController@disable');

        Route::group(['prefix' => 'subscriptions', 'as' => 'subscriptions.'], function() {
            Route::get('/',                                ['as' => 'index',        'uses' => 'SubscriptionController@index']);
            Route::get('/{subscription}',                  ['as' => 'edit',         'uses' => 'SubscriptionController@edit']);
            Route::put('/update',                          ['as' => 'update',       'uses' => 'SubscriptionController@update']);
            Route::post('/feature/save',                   ['as' => 'feature.save', 'uses' => 'SubscriptionController@featureStore']);
            Route::put('/feature/{feature_id}',            ['as' => 'feature.update', 'uses' => 'SubscriptionController@featureUpdate']);
            Route::get('/feature/{feature_id}',            ['as' => 'feature', 'uses' => 'SubscriptionController@getFeature']);
            Route::delete('/feature/{feature_id}',  ['as' => 'feature.delete', 'uses' => 'SubscriptionController@deleteFeature']);
        });
    });


    Route::group(['middleware' => ['auth', 'check.company']], function () {

        Route::post('profile/update_company',   ['as' => 'profile.update_company', 'uses' => 'UserController@updateProfileCompany']);

        Route::get('shop/{shop_id}/food_category/{food_category_id}/types', 'ShopController@getCategoryTypes');

        Route::get('/shop/invisible', 'ShopController@invisible');
        Route::get('/shop/visible', 'ShopController@visible');

        Route::get('/publish/request', 'ShopController@publishRequest');

        //Route::resource('shopCatalogs', 'ShopCatalogController');
        Route::group(['prefix' => 'shopCatalogs', 'as' => 'shopCatalogs.'], function() {
            Route::post('',                                 ['as' => 'store',   'uses' => 'ShopCatalogController@store'])->middleware('can:add_to_catalog');
            Route::get('',                                  ['as' => 'index',   'uses' => 'ShopCatalogController@index']);
            Route::get('create',                            ['as' => 'create',  'uses' => 'ShopCatalogController@create'])->middleware('can:add_to_catalog');
            Route::get('search',                            ['as' => 'search',  'uses' => 'API\ShopCatalogAPIController@search']);
            Route::get('/type-list/{food_category_id?}',    ['as' => 'types',   'uses' => 'API\ShopCatalogAPIController@getTypesList']);
            Route::patch('{shopCatalog}',                   ['as' => 'update',  'uses' => 'ShopCatalogController@update']);
            Route::delete('{shopCatalog}',                  ['as' => 'destroy', 'uses' => 'ShopCatalogController@destroy']);
            Route::get('{shopCatalog}/active',              ['as' => 'active',    'uses' => 'ShopCatalogController@setActive']);
            Route::get('{shopCatalog}',                     ['as' => 'show',    'uses' => 'ShopCatalogController@show']);
            Route::get('{shopCatalog}/edit',                ['as' => 'edit',    'uses' => 'ShopCatalogController@edit']);

            Route::group(['prefix' => 'multi', 'as' => 'multi.'], function() {

                Route::delete('delete', ['as' => 'delete',   'uses' => 'ShopCatalogController@multiDestroy']);
                Route::post('activate', ['as' => 'activate', 'uses' => 'ShopCatalogController@multiActivate']);
                Route::post('disable',  ['as' => 'active',   'uses' => 'ShopCatalogController@multiDisable']);

            });
        });

        //Route::resource('shopOffers', 'ShopOfferController');
        Route::group(['prefix' => 'shopOffers', 'as' => 'shopOffers.'], function() {
            Route::post('',                   ['as' => 'store',    'uses' => 'ShopOfferController@store']);
            Route::get('status/{shopOffer}',  ['as' => 'status',   'uses' => 'ShopOfferController@status']);

app/Models/ShopType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

/**
 * Class ShopType
 * @package App\Models
 * @version May 8, 2020, 10:43 am UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection $shops
 * @property string $name
 */
class ShopType extends Model
{

    public $table = 'shop_types';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';




    public $fillable = [
        'name'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];

    public static $messages = [
        'name.required' => 'Il nome è obbligatorio'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function shops()
    {
        return $this->belongsToMany(\App\Models\Shop::class, \App\Models\ShopShopType::class);
    }
}

resources/views/shops/edit_subscription.blade.php
@extends('adminlte::page')

@section('content')
<h3>{{ $user->shop->name }}</h3>

@php
    $expire_date = @\Carbon\Carbon::parse(old('subscription_date', $user->subscription->expire_date->format('Y-m-d')));
@endphp

<div class="clearfix"></div>

@include('flash::message')

{!! Form::open(array('url' => route('shopSubscription.update'), 'method' => 'post', 'id' => 'frm-edit-shop-subscription')) !!}

<input type="hidden" name="shop_id" value="{{ $user->shop->id }}">

<div class="row">

    {{--
    <div class="col-12">
        User id: {{ $user->id }}<br/>
        Shop id: {{ $user->shop->id }}<br/>
        User subscription id: {{ $user->subscription->id }}<br/>
        Partita IVA: {{ $user->shop->tax_vat }}
    </div>
     --}}

    <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
        <label for="subscription_id">Abbonamento</label>
        <select id="subscription_id" name="subscription_id" class="form-control">
            @foreach($subscriptions as $subscription)
            <option value="{{ $subscription->subscription }}" @if( $subscription->subscription === old('subscription_id', $user->subscription->subscription) ) selected @endif>{{ $subscription->name.' ('.$subscription->products_num.' prodotti)' }}</option>
            @endforeach
        </select>
    </div>
@if($user->subscription->subscription != 'free' || !empty($user->shop->agent_id))
    <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6 @if( $expire_date->isPast() ) has-error @endif">
        <label for="subscription_date">Data di scadenza</label>
        <input type="date" class="form-control @if( $expire_date->isPast() ) has-error @endif" id="subscription_date" name="subscription_date" value="{{ old('subscription_date', $user->subscription->expire_date->format('Y-m-d')) }}">
        @if( $expire_date->isPast() )
            <div class="alert alert-danger mt-1">L'abbonamento è scaduto</div>
        @endif
    </div>
@endif
	@php
		if($num_product_default){
			$product_num = 0;
		} else {
			$product_num = $user->subscription->subscription_product_num;
		}	
	@endphp
	<div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
        <label for="subscription_product_num">Numero prodotti personalizzato per l'abbonamento selezionato (inserire zero per il default)</label>
        <input type="number" class="form-control" id="subscription_product_num" name="subscription_product_num" value="{{ old('subscription_product_num', $product_num) }}">
    </div>

    @if( $other_shops_same_subscription->count() > 0 )
    <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
        <label for="other_shops_same_subscription">Altre attività incluse nell'abbonamento</label>
        <table class="table table-bordered table-hover">
            <thead class="bg-secondary">
                <tr>
                    <th>Rimuovi</th>
                    <th>Nome attività</th>
                    <th>Indirizzo</th>
                </tr>
            </thead>
            <tbody>
            @foreach($other_shops_same_subscription as $otherShop)
            <tr>
                <td><input type="checkbox" name="removeShops[]" value="{{ $otherShop->id }}"></td>
                <td>{{ $otherShop->name }}</td>
                <td>{{ $otherShop->address }}</td>
            </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @endif
</div>

@php
$remaining = 0;
if( $user->subscription->subscription !== 'trial' ){
    $remaining = $subscriptions[$user->subscription->subscription]->shops_num - $shops_in_subscription; //$other_shops_same_subscription->count() -1;
}
@endphp

@if( $user->status === 'active' )
    @if( $remaining > 0 && count($other_shops) > 0)
    <section class="bg-warning p-4 my-4 rounded">
        <div class="row">
            <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                <h3><strong>Puoi aggiungere {{ $remaining }} attività nello stesso abbonamento</strong></h3>

                <p>Seleziona attività</p>
                <table class="table table-striped bg-light">

                    @foreach($other_shops as $otherShop)
                    <tr>
                        <td><input type="checkbox" id="shop_id_{{ $otherShop->id }}" name="otherShops[]" value="{{ $otherShop->id }}"></td>
                        <td>{{ $otherShop->name }}</td>
                        <td>{{ $otherShop->address }}</td>
                    </tr>
                    @endforeach

                </table>

            </div>
        </div>
    </section>
    @elseif( $remaining > 0 && count($other_shops) === 0)
        <div class="text-center">
            <span class="badge badge-pill badge-warning my-4"><i class="fas fa-exclamation-triangle"></i> Puoi ancora associare {{ $remaining }} attività a questo abbonamento</span>
        </div>
    @elseif( $remaining === 0 )
        <div class="text-center">
            <span class="badge badge-pill badge-danger my-4"><i class="fas fa-exclamation-triangle"></i> Hai raggiunto il numero massimo di attività che puoi associare a questo abbonamento</span>
        </div>
    @endif
@endif

<section class="bg-primary p-2 rounded">
    <h3>Registra transazione</h3>
    <div class="row">
        <div class="form-group col-6">
            <label for="subscription_transaction_price">Importo</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">&euro;</span>
                </div>
                <input type="number" id="subscription_transaction_price" name="subscription_transaction_price" value="{{ old('subscription_transaction_price', '') }}" class="form-control" min="0.01" max="999999.99" step="any">
            </div>
            @error('subscription_transaction_price')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group col-6">
            <label for="subscription_transaction_mop">Metodo di pagamento</label>
            <select id="subscription_transaction_mop" name="subscription_transaction_mop" class="form-control">
                <option value="bonifico" @if( old('subscription_transaction_mop', 'bonifico') === 'bonifico') selected @endif>Bonifico</option>
                <option value="contanti" @if( old('subscription_transaction_mop', 'bonifico') === 'contanti') selected @endif>Contanti</option>
            </select>
        </div>

        <div class="form-group col-12">
            <label for="subscription_transaction_desc">Causale</label>
            <input type="text" id="subscription_transaction_desc" name="subscription_transaction_desc" value="{{ old('subscription_transaction_desc', '') }}" class="form-control">
            @error('subscription_transaction_desc')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
    <p>
        <small>Per registrare la transazione compilare tutti i campi</small>
    </p>
</section>

<div class="mt-4 text-center">
    <Button type="submit" class="btn btn-success">Salva</Button>
</div>

{!! Form::close() !!}

@if( $user->invoices )
    <section class="bg-secondary mt-4 p-2 rounded">
        <h3>Storico transazioni</h3>
        <div class="table-responsive">
            <table id="table-payments" class="table table-striped table-hover bg-light">
                <thead>
                    <th>Data</th>
                    <th>Utente</th>
                    <th>Causale</th>
                    <th>Importo</th>
                    <th>Metodo di pagamento</th>
                </thead>
                <tbody>
                    @foreach($user->invoices as $payment)
                    <tr>
                        <td>{{ $payment->created_at->format('d/m/Y H:i') }}</td>
                        <td>@if( $payment->user) {{ $payment->user->name }} @endif</td>
                        <td>{{ $payment->title }}</td>
                        <td>{{ number_format($payment->price, 2, ',', '.') }} &euro;</td>
                        <td>{{ $payment->method_of_payment }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </section>
@endif

@endsection

resources/views/shops/fields.blade.php
<!-- User Id Field -->
<!--div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div-->
<div class="row">
<!-- Tax Business Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tax_business_name', __('common.Tax Business Name').':') !!}
    {!! Form::text('tax_business_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Shop Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', __('common.Shop Types').':') !!}
    {!! Form::select('shop_type_id', $arr_shop_types, null, ['class' => 'form-control']) !!}
</div>

<!-- Tax Vat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tax_vat', __('common.Tax Vat').':') !!}
    {!! Form::text('tax_vat', null, ['class' => 'form-control']) !!}
</div>

<!-- Tax Fiscal Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tax_fiscal_code', __('common.Tax Fiscal Code').':') !!}
    {!! Form::text('tax_fiscal_code', null, ['class' => 'form-control']) !!}
</div>

<!-- Tax Address Field -->
<div class="form-group col-sm-6 col-lg-6">
    {!! Form::label('tax_address', __('common.Tax Address').':') !!}
    {!! Form::textarea('tax_address', null, ['class' => 'form-control', 'rows'=>2]) !!}
</div>

<!-- Min Trust Point Field -->
<div class="form-group col-sm-6">
    {!! Form::label('min_trust_point', __('common.Min Trust Point').':') !!}
    {!! Form::number('min_trust_point', null, ['class' => 'form-control']) !!}
</div>
<!-- Description Field -->
<div class="form-group col-sm-6 col-lg-6">
    {!! Form::label('description', __('common.description').':') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control', 'rows' => 3]) !!}
</div>

<!-- Delivery Methods Field -->
<div class="form-group col-sm-6">
    {!! Form::label('delivery_methods', __('common.Delivery Methods').':') !!}
    {!! Form::select('delivery_methods[]', $arr_delivery_methods, null, ['multiple' => 'multiple', 'class' => 'form-control']) !!}
</div>

<!-- Delivery Range Km Field -->
<div class="form-group col-sm-6">
    {!! Form::label('delivery_range_km', __('common.Delivery Range Km').':') !!}
    {!! Form::number('delivery_range_km', null, ['class' => 'form-control']) !!}
</div>

<!-- Excluded Commons Field -->
<div class="form-group col-sm-6 col-lg-6">
    {!! Form::label('excluded_commons', __('common.Excluded Commons').':') !!}
    {!! Form::textarea('excluded_commons', null, ['class' => 'form-control', 'rows' => 2]) !!}
</div>

<!-- Payment Methods Field -->
<div class="form-group col-sm-6">
    {!! Form::label('payment_methods', __('common.Payment Methods').':') !!}
    {!! Form::select('payment_method_id', $arr_payment_methods, null, ['class' => 'form-control']) !!}
</div>

<!-- Website Field -->
<div class="form-group col-sm-6 col-lg-6">
    {!! Form::label('website', __('common.Website').':') !!}
    {!! Form::textarea('website', null, ['class' => 'form-control', 'rows' => 1]) !!}
</div>

<!-- Facebook Page Field -->
<div class="form-group col-sm-6">
    {!! Form::label('facebook_page', __('common.Facebook Page').':') !!}
    {!! Form::text('facebook_page', null, ['class' => 'form-control']) !!}
</div>

<!-- Instagram Page Field -->
<div class="form-group col-sm-6">
    {!! Form::label('instagram_page', __('common.Instagram Page').':') !!}
    {!! Form::text('instagram_page', null, ['class' => 'form-control']) !!}
</div>

<!-- Opening Timetable Field -->
<div class="form-group col-sm-6 col-lg-6">
    {!! Form::label('opening_timetable', __('common.Opening Timetable').':') !!}
    {!! Form::textarea('opening_timetable', null, ['class' => 'form-control', 'rows' => 1]) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('common.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('shops.index') }}" class="btn btn-default btn-full">{{ __('common.cancel') }}</a>
</div>
</div>

resources/views/shops/index.blade.php
@extends('adminlte::page')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">{{ __('common.shops') }}</h1>
@if(Auth::user()->role == 'admin')
        <div class="pull-right  float-right d-none d-sm-block" >
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('shops.create') }}">{{ __('common.Add New') }}</a>
		</div>
@endif
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        {{--
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        --}}

        <div class="clearfix"></div>
        <div class="card card-primary">
            <div class="card-body">
                    @include('shops.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/shops/show.blade.php
@extends('adminlte::page')

@section('content')
    <section class="content-header">
        <h1>
            Shop
        </h1>
    </section>
    <div class="content">
        <div class="card card-primary">
            <div class="card-body">
                <div class="row" style="padding-left: 20px">
                    @include('shops.show_fields')
                    <a href="{{ route('shops.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shops/table.blade.php
<div class="table-responsive">
    <table class="table" id="shops-table">
        <thead>
            <tr>
                <th >{{ __('common.action') }}</th>
                <th>{{ __('common.Owner') }}</th>
                <th>Abbonamento</th>
                <th>{{ __('common.Shop Types') }}</th>
                <th>Nome attività</th>
                <th>Comune</th>
                <th>Prov</th>
                <th>Generato</th>
                <th>Avvisato</th>
                <th>Test</th>
                <th>Prod.</th>
                <th>{{ __('common.Agent') }}</th>
                <th>Stato</th>
            </tr>
        </thead>
        <tbody>
        @foreach($shops as $shop)
            <tr>
                <td>
                    {!! Form::open(['route' => ['shops.destroy', $shop->id], 'method' => 'delete']) !!}

                        <a href="{{ route('shops.edit', [$shop->id]) }}" class='btn btn-default btn-sm m-1' title="Modifica Attività"><i class="fas fa-edit"></i></a>
                        <a href="{{ route('shopSubscription.edit', [$shop->id]) }}" class='btn btn-default btn-sm m-1' title="Abbonamento"><i class="fas fa-credit-card"></i></a>

                        @if ($shop->user->status == "active" || $shop->user->status == "pending")
                            <a href="user/disable/{{ $shop->user->id }}" class='btn btn-danger btn-sm m-1'><i class="fas fa-user-times"></i></a>
                        @endif

                        @if ($shop->user->status == "inactive" || $shop->user->status == "pending")
                            <a href="user/enable/{{ $shop->user->id }}" class='btn btn-success btn-sm m-1'><i class="fas fa-user-check green"></i></a>
                        @endif

                    {!! Form::close() !!}
                </td>
                <td>{{ $shop->user->name }}</td>
                <td>
                    {{ $shop->user->subscription->subscription }}
                    <br>
                    <span @if( $shop->user->subscription->expire_date->isPast() ) class="text-danger" @endif>
                        <small>
                            <strong>
								@if($shop->user->subscription->subscription != 'free' || ($shop->user->subscription->subscription == 'free' && !empty($shop->agent_id)))
	                                @if( $shop->user->subscription->expire_date->isPast() )
    	                            Scaduto
        	                        @else
            	                    Scade
                	                @endif il {{ $shop->user->subscription->expire_date->format('d/m/Y') }}
								@endif
                            </strong>
                        </small>
                    </span>
                </td>
                <td>{{ $shop->shopType }}</td>
                <td>{{ $shop->name }}</td>
                <td>{{ $shop->city }}</td>
                <td>{{ $shop->prov }}</td>
                <td>{{ empty($shop->admin_generated) ? 'NO' : 'SI' }}</td>
                <td>{{ empty($shop->admin_sent_email_shop_created) ? 'NO' : 'SI' }}</td>
                <td>{{ empty($shop->admin_test_shop) ? 'NO' : 'SI' }}</td>
                <td>{{ $shop->shopCatalogs->count() }}</td>
                <td>
                    @if( $shop->agent )
                    {{ $shop->agent->name }}
                    @endif
                </td>
                <td>
                    @if( $shop->status === 'active' )
                        <span class="badge badge-success"><i class="fas fa-check"></i> Attivo</span>
                    @elseif( $shop->status === 'pending' )
                        <span class="badge badge-warning"><i class="fa fa-clock"></i> In attesa</span>
                    @elseif( $shop->status === 'inactive' )
                        <span class="badge badge-danger"><i class="fas fa-times-circle"></i> Disabilitato</span>
                    @elseif( $shop->status === 'invisible' )
                        <span class="badge badge-light"><i class="fas fa-user-secret"></i> Invisibile</span>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@section('js')
<script>
$(function () {
    $('#shops-table').DataTable({
        "language": {
            url: "{{ url('js/Italian.json') }}"
        },
        "paging":   true,
        "initComplete": function (settings, json) {
            $("#shops-table").wrap("<div style='overflow:auto; width:100%;position:relative;'></div>");
        },
        pageLength: 10,
        stateSave: true,
        columnDefs: [
            { width: "10%", orderable: false, targets: 0 },
            { width: "5%", orderable: true, targets: 5 },
            { width: "5%", orderable: true, targets: 6 }
        ]
    });
});
</script>
@endsection